[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "brs-xss"
version = "2.1.0"
description = "Context-aware async XSS scanner for CI/CD"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [{ name = "Brabus" }]
keywords = ["security", "xss", "dast", "sarif", "playwright", "bug-bounty", "ci-cd", "async", "context-aware"]

# Soft-bounded dependencies to keep CI stable while allowing minor updates
dependencies = [
  "aiohttp>=3.8,<4.0",
  "typer>=0.9,<0.21",
  "rich>=13.0,<14.0",
  "pyyaml>=6.0,<7.0",
  "jinja2>=3.1,<4.0",
  "babel>=2.12,<3.0",
  "polib>=1.2,<2.0",
  "playwright>=1.40.0,<1.60.0",
  "beautifulsoup4>=4.12.3,<4.13"
]

classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Operating System :: OS Independent",
  "Topic :: Security",
  "Topic :: Security :: Cryptography",
  "Intended Audience :: Developers",
  "Intended Audience :: Information Technology",
  "Intended Audience :: System Administrators",
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console"
]

[project.urls]
Homepage = "https://github.com/EPTLLC/brs-xss"
Documentation = "https://github.com/EPTLLC/brs-xss/wiki"
Issues = "https://github.com/EPTLLC/brs-xss/issues"
Changelog = "https://github.com/EPTLLC/brs-xss/releases"

[project.scripts]
brs-xss = "cli.main:app"

[project.optional-dependencies]
dev = [
  "pytest>=8,<9",
  "pytest-cov>=4,<5",
  "pytest-asyncio>=0.23,<0.24",
  "aresponses>=3,<4",
  "pyfakefs>=5,<6"
]

[tool.setuptools]
include-package-data = true
license-files = ["LICENSE"]

[tool.setuptools.packages.find]
where = ["."]
include = ["brsxss*", "cli*"]
namespaces = false

# Optional package_data hints (use MANIFEST.in for non-Python packaging)
# package-data can be handled via MANIFEST.in; keep include-package-data = true

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = false
warn_return_any = false
check_untyped_defs = false
disallow_untyped_defs = false

# MyPy errors reduced from 178 to 138 (22% improvement)
# Remaining errors are mostly missing annotations in complex structures
exclude = []

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
asyncio_mode = "auto"

[tool.coverage.run]
branch = true
source = ["brsxss", "cli"]

[tool.coverage.report]
show_missing = true
skip_covered = true

# Optional lint / formatting hints (uncomment if using)
# [tool.black]
# line-length = 100
# target-version = ['py310']

# Optional packaging metadata for reproducible builds
[tool.distutils]
# placeholder if setup.cfg compatibility needed

# End of file
