name: Docker multi-arch

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract version and build metadata
        id: meta
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=latest
          fi
          REPO_OWNER_LC=$(echo -n "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          PUSH=true
          TAGS="ghcr.io/${REPO_OWNER_LC}/brs-xss:${VERSION}"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "push=${PUSH}" >> "$GITHUB_OUTPUT"
          echo "tags=${TAGS}" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./Dockerfile
          push: ${{ steps.meta.outputs.push == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}

  # To also publish to Docker Hub, create a separate workflow or add steps with your secrets.
